version: '3'

vars:
  NAME: vault
  VAULT_VERSION: 1.19.0

tasks:
  all:
    cmds:
    - task: rebuild

  launch:
    preconditions:
      - test -f .env
      - test -f vault.hclic
    cmds:
      - multipass launch --name {{ .NAME }} -c 2 -m 1G -d 10G lts

  install:
    cmds:
      - |
        multipass transfer ./scripts/10_install.sh {{ .NAME }}:/tmp/install.sh
        multipass exec {{ .NAME }} -- sudo -E sh /tmp/install.sh {{ .VAULT_VERSION}}
    silent: true

  post-install:
    cmds:
      - |
        multipass transfer ./scripts/20_post_install.sh {{ .NAME }}:/tmp/post_install.sh
        multipass transfer vault.hclic {{ .NAME }}:/tmp/vault.hclic
        multipass exec {{ .NAME }} -- sudo -E sh /tmp/post_install.sh

  vault-init:
    cmds:
      - |
        ./scripts/30_vault_init.sh {{ .VAULT_ADDR }}
        sed -i '' "s#VAULT_ADDR=.*#VAULT_ADDR='{{ .VAULT_ADDR }}'#g" .env
        sed -i '' "s/VAULT_TOKEN=.*/VAULT_TOKEN=$(jq -r '.root_token' vault_init.json)/g" .env
        echo "VAULT_ADDR: {{ .VAULT_ADDR }}"
        echo "VAULT_TOKEN: $(jq -r '.root_token' vault_init.json)"
    silent: true
    vars:
      VAULT_ADDR:
        sh: echo "https://`multipass info {{ .NAME }} --format json | jq -r '.info.{{ .NAME }}.ipv4[0]'`:8200"

  clean:
    cmds:
      - multipass stop {{ .NAME }}
      - multipass delete --purge {{ .NAME }}
    ignore_error: true
    silent: true

  shell:
    cmd: multipass shell {{ .NAME }}

  logs:
    cmd: multipass exec {{ .NAME }} -- journalctl -u vault.service -f

  unseal:
    dotenv: [".env"]
    cmd: ./scripts/40_vault_unseal.sh

  rebuild:
    cmds:
      - task: clean
      - task: launch
      - task: install
      - task: post-install
      - task: vault-init

  restart:
    cmds:
      - multipass stop {{ .NAME }}
      - multipass start {{ .NAME }}

  start:
    aliases: ["up"]
    cmds:
      - multipass start {{ .NAME }}

  stop:
    aliases: ["down"]
    cmds:
      - multipass stop {{ .NAME }}

  ui:
    cmds:
    - |
      echo UI: {{.VAULT_ADDR}}
      #open {{.VAULT_ADDR}}/ui
      sed -i '' "s#VAULT_ADDR=.*#VAULT_ADDR='{{ .VAULT_ADDR }}'#g" .env
    vars:
      VAULT_ADDR:
        sh: echo "https://`multipass info {{ .NAME }} --format json | jq -r '.info.{{ .NAME }}.ipv4[0]'`:8200"
